version: 2.1

executors:
  linux-node12:
    machine:
      image: ubuntu-2004:202010-01
  linux-node14:
    machine:
      image: ubuntu-2004:202107-02
  linux-node16:
    machine:
      image: ubuntu-2004:202111-01
  # uncomment the following lines and add the executor to the parameters matrix once the CircleCI plan is upgraded
  # macos-node14:
  #   macos:
  #     xcode: 11.7

jobs:
  test:
    parameters:
      platform:
        type: executor
      test-name:
        type: string
    executor: << parameters.platform >>
    steps:
      - checkout
      - run:
          name: Versions
          command: ./scripts/versions.sh
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: << parameters.test-name >>
          command: npm run << parameters.test-name >>
  npm_publish:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run:
          name: Publish
          command: ./scripts/npm-publish.sh

workflows:
  test_and_publish:
    jobs:
      - test:
          matrix:
            parameters:
              platform: [linux-node12, linux-node14, linux-node16]
              test-name: [test-general-tests, test-configuration-tests]
      - npm_publish:
          context: shardlabs
          filters:
            branches:
              only:
                - master
          requires:
            - test
