version: 2.1

executors:
  linux-node14:
    machine:
      image: ubuntu-2004:202107-02
  macos-node14:
    macos:
      xcode: 11.7
    environment:
      TERM: xterm-256color
    

jobs:
  test:
    parameters:
      platform:
        type: executor
      test-name:
        type: string
    executor: << parameters.platform >>
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: << parameters.test-name >>
          command: npm run << parameters.test-name >>
  npm_publish:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run:
          name: Publish
          command: ./scripts/npm-publish.sh


workflows:
  test_and_publish:
    jobs:
      - test:
          matrix:
            parameters:
              platform: [linux-node14, macos-node14]
              test-name: [test-general-tests, test-configuration-tests, test-venv-tests]
            exclude:
              - platform: macos-node14
                test-name: test-general-tests
              - platform: macos-node14
                test-name: test-configuration-tests
      - npm_publish:
          context: shardlabs
          filters:
            branches:
              only:
                - master
          requires:
            - test
