version: 2.1

aliases:
  - &node-base
    steps:
      - checkout
      - run:
          name: Versions
          command: ./scripts/versions.sh
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
  - &run-general-tests
      - run:
          name: Test
          command: npm run test-general-tests
  - &run-configuration-tests
      - run:
          name: Test
          command: npm run test-configuration-tests

          
jobs:
  general_test_node_v12:
    <<: *node-base
      <<: *run-general-tests
    machine:
      image: ubuntu-2004:202010-01
  general_test_node_v14:
    <<: *node-base
      <<: *run-general-tests
    machine:
      image: ubuntu-2004:202107-02
  configuration_test_node_v12:
    <<: *node-base
      <<: *run-configuration-tests
    machine:
      image: ubuntu-2004:202010-01
  configuration_test_node_v14:
    <<: *node-base
      <<: *run-configuration-tests
    machine:
      image: ubuntu-2004:202107-02
  npm_publish:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run:
          name: Publish
          command: ./scripts/npm-publish.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - general_test_node_v12
      - general_test_node_v14
      - configuration_test_node_v12
      - configuration_test_node_v14
      - npm_publish:
          context: shardlabs
          filters:
            branches:
              only:
                - master
          requires:
            - general_test_node_v12
            - general_test_node_v14
            - configuration_test_node_v12
            - configuration_test_node_v14
