version: 2.1

aliases:
  - &node-base
    steps:
      - checkout
      - run:
          name: Versions
          command: ./scripts/versions.sh
      - run:
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test

jobs:
  test_node_v12:
    <<: *node-base
    machine:
      image: ubuntu-2004:202010-01
  test_node_v14:
    <<: *node-base
    machine:
      image: ubuntu-2004:202107-02
  npm_publish:
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run:
          name: Publish
          command: ./scripts/npm-publish.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test_node_v12
      - test_node_v14
      - npm_publish:
          context: shardlabs
          filters:
            branches:
              only:
                - master
          requires:
            - test_node_v12
            - test_node_v14
