#!/bin/bash

set -u

export OZ_ACCOUNT_ADDRESS=$OZ_ACCOUNT_ADDRESS_ALPHA
export OZ_ACCOUNT_PRIVATE_KEY=$OZ_ACCOUNT_PRIVATE_KEY_ALPHA

export ARGENT_ACCOUNT_ADDRESS=$ARGENT_ACCOUNT_ADDRESS_ALPHA
export ARGENT_ACCOUNT_PRIVATE_KEY=$ARGENT_ACCOUNT_PRIVATE_KEY_ALPHA
